# Generated by Django 5.2.2 on 2025-08-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_condition'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('open_box', 'Open Box'), ('used', 'Used'), ('damaged', 'Damaged'), ('missing_parts', 'Missing Parts')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_sellable', models.BooleanField(default=False)),
                ('seller_approval', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_products', to='products.product')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_products', to='returns.returnrequest')),
            ],
            options={
                'unique_together': {('product', 'return_request', 'status')},
            },
        ),
    ]
