# Generated by Django 5.2.2 on 2025-08-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('under_inspection', 'Under Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=30),
        ),
    ]
