# Generated by Django 5.2.2 on 2025-08-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_returnrequest_quantity_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('under_inspection', 'Under Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=30),
        ),
    ]
