# Generated by Django 4.2.20 on 2025-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="current_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_token_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
