# Generated by Django 4.2.20 on 2025-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverification_current_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="new_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("ChangeEmail", "Email Change"),
                ],
                max_length=30,
            ),
        ),
    ]
