# Generated by Django 5.2.2 on 2025-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification_new_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
