# Generated by Django 5.2.2 on 2025-06-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification_is_certified_profile_is_certified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='is_certified',
        ),
    ]
