# Generated by Django 5.2.2 on 2025-08-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_held_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('payment', 'Payment'), ('refund', 'Refund'), ('fee', 'Fee'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('seller_debit', 'Seller Debit')], max_length=20),
        ),
    ]
