# Generated by Django 5.2.2 on 2025-08-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
