# Generated by Django 5.2.2 on 2025-07-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('order_created', 'Order Created'), ('order_shipped', 'Order Shipped'), ('system_alert', 'System Alert'), ('wishlist_discount', 'Wishlist Discount')], max_length=20),
        ),
    ]
