# Generated by Django 5.2.2 on 2025-08-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('order_created', 'Order Created'), ('order_shipped', 'Order Shipped'), ('system_alert', 'System Alert'), ('wishlist_discount', 'Wishlist Discount'), ('order_created', 'Order Created'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('refund_rejected', 'Refund Rejected'), ('seller_payment', 'Seller Payment'), ('seller_verified', 'Seller Verified')], max_length=20),
        ),
    ]
