# Generated by Django 5.2.2 on 2025-06-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_approved_at_product_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
