# Generated by Django 5.2.2 on 2025-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disapproval_reason',
            new_name='disapproval_reason_ar',
        ),
        migrations.AddField(
            model_name='product',
            name='disapproval_reason_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
