# Generated by Django 5.2.2 on 2025-07-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_disapproval_reason_product_disapproval_reason_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_child': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
