# Generated by Django 5.2.2 on 2025-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Available quantity of this product', verbose_name='Quantity in stock'),
        ),
    ]
