# Generated by Django 5.2.2 on 2025-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_saleevent_productsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='saleevent',
            name='name',
        ),
        migrations.AddField(
            model_name='saleevent',
            name='description_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='saleevent',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='saleevent',
            name='name_ar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='saleevent',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
