# Generated by Django 5.2.2 on 2025-07-25 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_saleevent_description_remove_saleevent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_standalone_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='standalone_discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='standalone_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='standalone_discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
