# Generated by Django 5.2.2 on 2025-08-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_has_standalone_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('damaged', 'Damaged'), ('unsaleable', 'Unsaleable')], default='new', max_length=20),
        ),
    ]
