# Generated by Django 5.2.2 on 2025-08-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_brandblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/'),
        ),
    ]
