# Generated by Django 5.2.2 on 2025-08-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_category_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producteditrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='producteditrequest',
            old_name='new_description_ar',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='producteditrequest',
            old_name='new_description_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='producteditrequest',
            old_name='new_name_ar',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='producteditrequest',
            old_name='new_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='producteditrequest',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='producteditrequest',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='producteditrequest',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand'),
        ),
        migrations.AddField(
            model_name='producteditrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='producteditrequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producteditrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producteditrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='editrequestimage',
            name='edit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_images', to='products.producteditrequest'),
        ),
        migrations.AlterField(
            model_name='producteditrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='products.product'),
        ),
    ]
